language: cpp
sudo: true

compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get -y remove ffmpeg
  - sudo apt-get -y install libxvidcore-dev ffmpeg

install:
  - wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
  - bii setup:cpp
  - bii --version

script:
  - bii init -L && bii build && bii test

notifications:
  email: false
