language: cpp
sudo: true

compiler:
  - gcc

install:
  - wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
  - bii setup:cpp
  - bii --version

script:
  - bii init -L
  - bii find
  - bii configure
  - bii build

notifications:
  email: false
