language: cpp
sudo: true

compiler:
  - clang
  - gcc

env:
  global:
    - GCC_VERSION="4.9"

before_install:
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi
  - sudo apt-get update -qq

  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq g++-${GCC_VERSION}; fi
  - if [ "$CXX" == "g++" ]; then sudo apt-get install -qq gcc-${GCC_VERSION}; fi
  - if [ "$CXX" == "g++" ]; then sudo ln -s -v -f $(which g++-${GCC_VERSION}) /usr/bin/g++; fi
  - if [ "$CXX" == "g++" ]; then sudo ln -s -v -f $(which gcc-${GCC_VERSION}) /usr/bin/gcc; fi

install:
  - wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
  - bii setup:cpp
  - bii --version

script:
  - bii init -L
  - bii find
  - bii configure
  - if [ "$CXX" == "clang++" ]; then export CXX="clang++" && bii build; fi
  - if [ "$CXX" == "g++" ];     then export CXX="g++"     && bii build; fi

cache:
  directories:
    - '$HOME/.biicode'

notifications:
  email: false
