language: cpp
sudo: true

compiler:
  - gcc

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

  - wget http://apt.biicode.com/install.sh && chmod +x install.sh && ./install.sh
  - bii setup:cpp
  - bii --version

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

script:
  - bii init -L
  - bii build

cache:
  directories:
    - '$HOME/.biicode'

notifications:
  email: false
